### ISSUE TITLE
🚨 Establish Linux Support

### ISSUE THREAD

**Issue by Blackjacx** [Blackjacx/Assist#10]
Fix this error with Swift-style pre-compiler macros:

```
[925/930] Compiling Core Json.swift
/host/Sources/Core/Networking/JSONWebToken.swift:96:26: error: cannot find 'URLRequest' in scope
        var urlRequest = URLRequest(url: URL(string: credentials.tokenUrl)!)
                         ^~~~~~~~~~
/host/Sources/Core/Networking/JSONWebToken.swift:101:23: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
```

## Acceptance Criteria
- check back on [Package Index](https://swiftpackageindex.com/Blackjacx/Assist) if it worked

# Todos
- [x] Use `FoundationNetworking` on Linux
- [x] Remove `PersonNameComponentsFormatter` since it is not supported in core foundation
- [x] Configure Github Actions to run on ubuntu
- [x] Make it work on [Package Index](https://swiftpackageindex.com/Blackjacx/Assist)
